#!/bin/bash
# Quick Start Guide - Chạy workflow ở local

echo "🚀 QUICK START - Chạy Workflow Ở Local"
echo "======================================"
echo ""
echo "📋 Bước 1: Setup secrets (chỉ cần làm 1 lần)"
echo "   ./setup-secrets.sh"
echo "   nano .secrets  # Điền API keys vào đây"
echo ""
echo "📋 Bước 2: Chạy workflow"
echo ""
echo "   # Chạy pipeline 'others' (topcv,twitter,indeed,vercel,cloudflare,topdev,itviec)"
echo "   ./run-local.sh"
echo ""
echo "   # Hoặc chạy platform cụ thể:"
echo "   ./run-local.sh itviec"
echo "   ./run-local.sh \"topcv,itviec\""
echo "   ./run-local.sh facebook"
echo "   ./run-local.sh threads"
echo ""
echo "📋 Bước 3: Xem kết quả"
echo "   ls -lht logs/job-search-*.json | head -1"
echo "   cat logs/job-search-*.json | jq ."
echo ""
echo "📚 Xem hướng dẫn chi tiết: cat LOCAL_WORKFLOW.md"
echo ""
