#!/bin/bash
# Quick Start Guide - Run workflow locally

echo "🚀 QUICK START - Local Workflow Execution"
echo "=========================================="
echo ""
echo "📋 Step 1: Setup secrets (Required once)"
echo "   ./setup-secrets.sh"
echo "   nano .secrets  # Enter your API keys here"
echo ""
echo "📋 Step 2: Run workflow"
echo ""
echo "   # Run the 'others' pipeline (topcv, twitter, indeed, vercel, cloudflare, topdev, itviec)"
echo "   ./run-local.sh"
echo ""
echo "   # Or run a specific platform:"
echo "   ./run-local.sh itviec"
echo "   ./run-local.sh \"topcv,itviec\""
echo "   ./run-local.sh facebook"
echo "   ./run-local.sh threads"
echo ""
echo "📋 Step 3: View results"
echo "   ls -lht logs/job-search-*.json | head -1"
echo "   cat logs/job-search-*.json | jq ."
echo ""
echo "📚 Detailed Guide: cat LOCAL_WORKFLOW.md"
echo ""
